@rinkebyhost = 
@mainnethost = 
@localhost = http://localhost:8080
@hostname = {{localhost}}


### Health check
GET {{hostname}}/v1/health
Content-Type: application/json

### Query Order
Get {{hostname}}/v1/orders
?collection=0x78c3E13fdDC49f89feEB54C3FC47d7df611FA9BE
&side=1
content-type: application/json


### Get Order by hash
Get {{hostname}}/v1/orders/0xdc62be9add23f8f689987d0dfd199befd374c8b3ff914bfe4b231bd6e294d6e2

### Prepare Order Execution
Post {{hostname}}/v1/orders/0xdc62be9add23f8f689987d0dfd199befd374c8b3ff914bfe4b231bd6e294d6e2/prepare
Content-Type: application/json

{
  "maker": "0xE1d7a59AB392EA29b059dAE31c5A573e2fEcC5A8",
  "amount": "100000000000000000000",
  "revenueSplits": [
    {
      "account": "0x3bB0dE46c6B1501aF5921Fb7EDBc15dFD998Fadd",
      "value": "5000"
    }
  ]
}


### Encode or Create Seller Order
POST {{hostname}}/v1/orders/encoder/order
Content-Type: application/json

{
  "type": "UNIVERSE_V1",
  "maker": "0xE1d7a59AB392EA29b059dAE31c5A573e2fEcC5A8",
  "taker": "0x0000000000000000000000000000000000000000",
  "make": {
    "assetType": {
      "assetClass": "ERC721",
      "contract": "0x78c3E13fdDC49f89feEB54C3FC47d7df611FA9BE",
      "tokenId": 2
    },
    "value": "1"
  },
  "take": {
    "assetType": {
      "assetClass": "ETH"
    },
    "value": "100000000000000000"
  },
  "salt": 3,
  "start": 0,
  "end": 0,
  "data": {
    "dataType": "ORDER_DATA",
    "revenueSplits": [
      {
        "account": "0x3bB0dE46c6B1501aF5921Fb7EDBc15dFD998Fadd",
        "value": "5000"
      }
    ]
  },
  "signature": "0x87891ef19fd0169ae39b323d9b0c235a5d7cfeefec8a184d2612e76e1ebf974667b6addb8c28215aadd95322475e4c3c57f381a44809f0fd5eda30be42b97e501c"
}

### Encode or Create Sell Bundle
POST {{hostname}}/v1/orders/order
Content-Type: application/json

{
  "type": "UNIVERSE_V1",
  "maker": "0xE1d7a59AB392EA29b059dAE31c5A573e2fEcC5A8",
  "taker": "0x0000000000000000000000000000000000000000",
  "make": {
    "assetType": {
      "assetClass": "ERC721_BUNDLE",
      "contracts": ["0x78c3E13fdDC49f89feEB54C3FC47d7df611FA9BE"],
      "tokenIds": [[3, 4]]
    },
    "value": "2"
  },
  "take": {
    "assetType": {
      "assetClass": "ETH"
    },
    "value": "200000000000000000"
  },
  "salt": 4,
  "start": 0,
  "end": 0,
  "data": {
    "dataType": "ORDER_DATA",
    "revenueSplits": [
      {
        "account": "0x3bB0dE46c6B1501aF5921Fb7EDBc15dFD998Fadd",
        "value": "5000"
      }
    ]
  },
  "signature": "0x21763f7b9c4d123cff32079364e8593381cb62057d54aa017691a5df2b6f51d52afe6c7e889f701fbf9299cc80a4ed9339f3d2bff1b2c1fd9b4d358b3b5ffc991b"
}

### Encode or Create Buy Order
POST {{hostname}}/v1/orders/order
Content-Type: application/json

{
  "type": "UNIVERSE_V1",
  "maker": "0xa035F2A1fC34fec7EfbD2E9cA2d567c5Cc001d91",
  "taker": "0x0000000000000000000000000000000000000000",
  "take": {
    "assetType": {
      "assetClass": "ERC721",
      "contract": "0x78c3E13fdDC49f89feEB54C3FC47d7df611FA9BE",
      "tokenId": 5
    },
    "value": "1"
  },
  "make": {
    "assetType": {
      "assetClass": "ERC20",
      "contract": "0x7aD29Fbf3Cfa3F53B9d8a79ea0870b402E642Cac"
    },
    "value": "100000000000000000000"
  },
  "salt": 5,
  "start": 0,
  "end": 0,
  "data": {
  },
  "signature": "0x869161c3ef20ef4769c3e786cd8ff19f5154e90d3aa5d8ce6f6f159c30a05d3271b242675e5f55f93d020a32f55db80dd03b722bbc4088e2b56ac75ebee88d811b"
}

### Match Order
PUT {{hostname}}/v1/orders/0x7a711e9b7ee5c5ff8dcb41f0815e9104e7d074b4f153cbbddaef0637276bc0ec/match
Content-Type: application/json

{
  "txHash": "",
  "leftMaker": "",
  "rightMaker": "",
  "leftOrderHash": "",
  "rightOrderHash": "",
  "newLeftFill": "",
  "newRightFill": ""
}


### subgraph health
POST https://api.thegraph.com/index-node/graphql
Content-Type: application/json

{
  "query": `{
  indexingStatusForCurrentVersion(subgraphName: "org/subgraph") {
    synced
    health
    fatalError {
      message
      block {
        number
        hash
      }
      handler
    }
    chains {
      chainHeadBlock {
        number
      }
      latestBlock {
        number
      }
    }
  }
}`
}

### subgraph
POST https://api.thegraph.com/subgraphs/name/kunone/marketplace-rinkeby-v2
Content-Type: application/json

{
  "query": `{
      orderMatchEntities(first: 1, orderBy: blockNumber, orderDirection: asc, where: {blockNumber_gte: 0}) {
        id
        txFrom
        txValue
        blockNumber
        blockTimestamp
        leftOrderHash
        rightOrderHash
        leftMaker
        rightMaker
        newLeftFill
        newRightFill
        leftAssetClass
        rightAssetClass
        leftAssetData
        rightAssetData
      } 
    }`
}